# Generated by Django 5.1.5 on 2025-02-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_payment_box_choice_remove_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='box_choice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-08 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='reward',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rewardpayment',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
