# Generated by Django 5.1.5 on 2025-02-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reward',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rewardpayment',
            name='reward',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
