# Generated by Django 5.1.5 on 2025-02-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_payment_reward_alter_rewardpayment_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reward',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rewardpayment',
            name='reward',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
